import React from "react";
import About from "./page";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Socila Media - Ads and Seo - For more beutiful Hause ",
  description: "Generated by create next app",
};

function layout() {
  return (
    <div>
      <About />
    </div>
  );
}

export default layout;
