import React from "react";
import Strategy from "./page";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Socila Media - Ads and Seo - For more beutiful Hause ",
  description: "Generated by create next app",
};

function layout() {
  return (
    <section>
      <div>
        <Strategy />
      </div>
    </section>
  );
}

export default layout;
