import React from "react";
import Grow from "./page";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Grow - For more beutiful Hause ",
  description: "Generated by create next app",
};

function layout() {
  return (
    <section>
      <div>
        <Grow />
      </div>
    </section>
  );
}

export default layout;
