import type { Metadata } from "next";
import { Manrope, Space_Grotesk } from "next/font/google";
import "./globals.css";
import Hero1 from "@/components/LandingPage/Hero1";
import Footer from "@/components/LandingPage/Footer";

const Space = Space_Grotesk({
  variable: "--Grotesk",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const manrope = Manrope({
  variable: "--Manrope",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Premium - Next.js Design, development, smma, busness automation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Space.variable} ${manrope.variable} antialiased`}>
        <Hero1 />
        {children}
        <Footer />
      </body>
    </html>
  );
}
