import React from "react";
import WebDesgin from "./page";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "WebDesgin - For more beutiful Hause ",
  description: "Generated by create next app",
};

function layout() {
  return (
    <section>
      <div>
        <WebDesgin />
      </div>
    </section>
  );
}

export default layout;
